
@startuml

title: Diagrama Academia

class User {
    - nome: String
    - endereco: String
    - telefone: String
    - email: String
    - senha: String
    - tipoUsuario: tipo
    + construtor(nome, edereco, telefone, email, senha)      
    + cadastrarUsuario(nome, edereco, telefone, email, senha)
    + buscarUsuario(nome)                 
    
}

class Gym{
    - name : String
    - addres : String
    - cnpj: String
    + construtor(cnpj)
    + cadastrarcnpj(cnpj)
    + adicionarAluno(student: Student)
    + adicionarInstrutor(instructor: Instructor)

}


class Training{
    - exercises: Exercises
    - data: date
    - hora: String
    - observacoes: String
    - gym : Gym
    - user : User

    + construtor(tipoExercicio, peso, repeticoes)
    + cadastrarTreino(tipoExercicio, peso, repeticoes)
}

class Exercises{
    - tipoExercicio: String
    - peso: int
    - repeticoes: int
    + construtor(tipoExercicio, peso, repeticoes)
    + cadastrarTreino(tipoExercicio, peso, repeticoes)
}

class FoodPlan{
    - alimento: String
    - quantidade: int
    - user
    + construtor(alimento, quantidade)
    + cadastrarPlanoAlimentar(alimento, quantidade)
}





Gym --* Training
Training *-- Exercises
Training *-- User
FoodPlan *-- User






@enduml